
version: '3'
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - mongo
  frontend:
    build: ./frontend
    ports:
      - "9000:9000"
